name: CI Workflow Diff Test # ワークフローの名前

on: # トリガー条件
  pull_request_review:
    types: [submitted]
  # Manual trigger
  workflow_dispatch:

jobs:
  diff_test:
    # Run only when 'ready_for_review' event is triggered
    name: Test for PR
    if: ((github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'develop') && github.event_name == 'pull_request_review') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Yarn # Yarnのセットアップ
        run: npm install -g yarn

      - name: Install dependencies # 依存関係のインストール
        run: yarn install

      - name: Get changes since base branch
        id: changes
        run: |
          git fetch origin
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"  # ベースブランチの名前を取得
          MODIFIED_FILES=$(git diff --name-only origin/$BASE_BRANCH..${{ github.event.pull_request.head.sha }})  # 差分ファイルを環境変数に保存
          echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV

      - name: Run Jest tests for related files
        if: env.MODIFIED_FILES
        run: |
          yarn test related ${{ env.MODIFIED_FILES }}   # 関連するテストを実行

  full_test:
    if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
    runs-on: ubuntu-latest # 実行環境
    steps:
      - name: Checkout code # リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Set up Node.js # Node.js環境のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Node.jsのバージョン

      - name: Install Yarn # Yarnのセットアップ
        run: npm install -g yarn

      - name: Install dependencies # 依存関係のインストール
        run: yarn install

      - name: Run tests # テストの実行
        run: yarn test
